language: python
python:
  - "python-3.11.0.tar.bz2"  # Use the development version of Python 3.10

env:
  - DJANGO_SETTINGS_MODULE="mysite.settings"

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test
