dist: jammy
language: python
python:
  - "3.10.8"  # Use the development version of Python 3.10

env:
  - DJANGO_SETTINGS_MODULE="mysite.settings"

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test  # Run tests with coverage
  - coverage report  # Generate coverage report
  after_success:
  - coveralls


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "swe1-app"
  env: "swe1-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-891377257918"
  on:
    branch: main  # Deploy only from the main branch
